sudo: false
language: java
install: true
cache:
  directories:
  - "$HOME/.m2"
before_install:
- "./scripts/status-checks.sh verify"
script:
- "./scripts/status-checks.sh test"
- "./scripts/status-checks.sh coverage"
after_success: 
env:
  global:
  - secure: IORWyb/2GJdnuOnCjNGJTxaR3mfImKEeqpX6xhb/Y5l7cyY30NViwQR8TCVgz/fX6jTZqqU9NDgdmRMDqpyx+lG/HW0eiPCPNcqwVYTaLVaIJbMpcZfPn5hSPM/lZqbgZb4T7RYWZ60X79tpjYbfLuvMhvEwP3u2K1Su97VFOdw=
  - secure: WYCDoeFkfFDSCU40mwAEKCH1OLSqU8pOXpewm8SyzvJqownJ9As3tz0rl/yjgGd2Y69EcxjBxuqgEjhF6PeTJ6hmr7W30Uv5njEeSfkYNFMAdWOmy16fJXZ/fStPKqykstHo8G9La+ioXfTH/olb63FM9+sxCi26TdZzPZC51SU=
