sudo: false
language: java
cache:
  directories:
  - "$HOME/.m2"
before_install:
- "./bogus-status-check.sh"
after_success:
- mvn clean site
env:
  global:
    secure: IORWyb/2GJdnuOnCjNGJTxaR3mfImKEeqpX6xhb/Y5l7cyY30NViwQR8TCVgz/fX6jTZqqU9NDgdmRMDqpyx+lG/HW0eiPCPNcqwVYTaLVaIJbMpcZfPn5hSPM/lZqbgZb4T7RYWZ60X79tpjYbfLuvMhvEwP3u2K1Su97VFOdw=
deploy:
  provider: heroku
  api_key:
    secure: b6jcu57oI6g8ZKKQxATF7qLNX36k5oI2B6Z2Yf31MX5Q/OFcDqgZiBqEYVHZ1TtyVcfNdTtMxtAAY3rSp1h7epMPUD197QhfUM4lDzfS/rf2RXTrxTcpZ8L05BlOb8GrTDaQPtcqV6IzkyEkYDEfJPRTbjQQc5jKPUula9pvdpg=
  app: reading-time-app
  on:
    repo: office-tools/reading-time-app
