sudo: false
language: java
install: true
cache:
  directories:
  - "$HOME/.m2"
before_install:
- "./scripts/status-checks.sh verify"
script:
- "./scripts/status-checks.sh test"
- "./scripts/status-checks.sh coverage"
after_success: 
env:
  global:
  - secure: gUXxZ+ohJf7lhOSfJAxw8++97tQmlNPpGqZwm4HchdEcL6DDJQe+OarZxM1j+t+RqmEdSY1AOmRxmrD3lFQKn8BQbUNQqbCmOtCQiqEArAoP7VTLKq3CcqAkuyhbRg4AB8al2xgML/inBptJJShHxiol5yQGmaenpbYnx91ZSPHZmTpZE8Y9qiCCzvY4/QQoOC/tqwUNm10QhWDJcHbSxIlXkL8pQW2x0IG8C4CAS/JJWVZwK/AhpcpIMESLaJbDUeNhJUlQwIiii+/K2/QoRHVjpn/tWyAygB0WUyhxRK5qZIbMQo1kn07UnC5W6PA5we5I+AT7gNm/auYw3pSPIbE93uNce1sTmfBRk5qcyqANHXZOF8zxfL1lnQXzcVM5aEOqMTCz1JfEJef4amORRBKyZ0aDVuUGYiHXNumARQq7UXia9XksoeFK/yPyUUI3Vu2KCKBoIL7W2UTA3rLTbEZwWUM4GNuz6nVGX4ZcqHsKEjFBAY4VimwTAYMrKPiXST5HDFAKrrQLWerMBieKVtf/GLFAOjYijBZGPAK38508mL6hSk6LRS1Q/SWWeKoAH1tsx7NuV4rt4YpBFiQupFW0ZJuY9Gc/DN+JCWxiIuAIn+cq7ZDeSCtVhNkizh0dRmSfUBHtyHvowu4dyh4LbONg8TGPsf8wQNcFM4s86Tk=
  - secure: Ev3Zvagh1k6S0aEHKuBGcwwZDavYDgYvQVNF0XaYG+1js1cYttzTaR6dRVRrmgYU+/tM5PgOp2gkrG0moKbXClmpDgIoqS5FRyEbBZ38mAEIq1uRKgYlo9BNBkrdPaTrKgkmx6WT8AAsIw9sDo0/FbMxzIXlsj2eHHd/5GeB4tJFh8oqeDAS+1+CtMh9y27HczKCPk6vAFy2roDRxymO68qEUJi+boJlfli0r+tKOjvHnEYetZXDxfzFAlcFWHS5tGWRTk6ORleSH/fxktrNmzx+HrsqKPu15IHenTWsGQl6eAtJDpIld2zQny8rvLmHcoRKASBCMSG0rW/9g2zsJ2+cR7zoyScuJXYqgpg+1qPXDwTwqa5WTS3uEo+m1UzHd4iwWiO7b7RWCt+u8BB2NSLRYzUyqZr8/lge3W7AZykp6MnHw5XKrsHIUzZz3HViEXOULNYTSgoADT28pavFV+1m9E7/paWqiui369/ighoAgB/YYjVsHHWokulXgv9eW8Vjo+XCZr3Qi9QzXYnsIUgdUjz0U1tvzs/LvKUysxsRdN1t0x7xxI2TG0Q6ujWTsb5OU5MGi2KvvIB2G4T3HDLt53zDtRHKR7qumRMoQpCMQBwZELw9wIxABvegQr48f5X+yy5Vk4pNDKkPIy0nJorZs/KbNvUUrnE2RMo+i+A=
