sudo: false
language: java
install: true
cache:
  directories:
    - $HOME/.m2
before_install:
  - function statuses () {
  -  curl -H "Authorization: Token $TOKEN" -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"state": "'"$1"'","target_url": "https://travis.octodemo.com/'$TRAVIS_REPO_SLUG'","description": "'"$2"'","context": "checkstyle-status-check/travis-ci"}' https://octodemo.com/api/v3/repos/${TRAVIS_REPO_SLUG}/statuses/$TRAVIS_COMMIT
  - }
  - statuses "pending" "Checking Java code against coding standards"
  - mvn verify -DskipTests=true
  - STATUS=$?
  - echo "$STATUS"
  - if [ $STATUS -eq 0 ]; then
  -  statuses "success" "Java code meets coding standards"
  - else
  -  statuses "failure" "Java code does not meeting coding standards"
  - fi
script:
  - mvn install -DskipTests=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B -Dcheckstyle.skip=true
after_success:
  - ./after-success.sh
env:
  global:
    secure: IORWyb/2GJdnuOnCjNGJTxaR3mfImKEeqpX6xhb/Y5l7cyY30NViwQR8TCVgz/fX6jTZqqU9NDgdmRMDqpyx+lG/HW0eiPCPNcqwVYTaLVaIJbMpcZfPn5hSPM/lZqbgZb4T7RYWZ60X79tpjYbfLuvMhvEwP3u2K1Su97VFOdw=
