sudo: false
language: java
install: true
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    secure: DEi7cRjWa14LjvGGwdFF2X8PdRrH29pSdOdFKqwXA/W2uvzgNvXVdOfAlzs//nmIZpIfS9WmV1roXomCu0y9SgSQLhsbk2xq9mQyJpjpGvFub0lgTK2D0bnCdDcpBbqCV+ZOJSE+srLS/94QK//8rjV7xkec6qkGG9XtR0JiI5j4IyinqybKG6LKq/j4PMcrWb5fGID+o6wleCbihma/hXaAZ5RyQJMBOvBvYeyFG0u/QhRl6qv7n2Xvz5wVGbuERZNrLp0LwNsQILp+KF1vob1C9kdd6c1EyULxfAiYN/uzvB6IZigC1vWu6DDpqjscFH37Y8TOWiI1aUCRwiq5CvLqAPADaLsdjmPi5e1hbl5TAu2dIvB1byCgG6NqN0giq+a07jgE4fXrVrkANuKqBSaerGyVLRGbVqdUtYiQZG/i2TQxLK3nvX9w+mtiPxzMbsBewmZJnsJCWlkLYybxmZLc//TcEBvRKpmFSgG0x/2DIJ8RyaSpL4X/5UBb+vmf0D3rBgck00ofk+VwP8zxcrNqwKYstMhws2GRkcE5y0k+gBRoF0FS0FDh5dC/jDf173GWCQgn2xBC40BXZny5o4v+ypMvd83Mv/3Gw6+QeWbIxZ+B34fpmeiFgFiOvE9BjG7iC+JnrFeu38rLERW0KQauXEYlfz3eb7z9eF/sxwc=
