sudo: false
language: java
install: true
cache:
  directories:
    - $HOME/.m2
before_install:
  - ./scripts/status-checks.sh verify
script:
  - mvn install -DskipTests=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -B -V
  - ./scripts/status-checks.sh test
after_success:
  - ./scripts/status-checks.sh site
  - ./scripts/deploy.sh
env:
  global:
    secure: IORWyb/2GJdnuOnCjNGJTxaR3mfImKEeqpX6xhb/Y5l7cyY30NViwQR8TCVgz/fX6jTZqqU9NDgdmRMDqpyx+lG/HW0eiPCPNcqwVYTaLVaIJbMpcZfPn5hSPM/lZqbgZb4T7RYWZ60X79tpjYbfLuvMhvEwP3u2K1Su97VFOdw=
