on: [push]

name:  Maven

jobs:

  build:
    name: Build
    container:
      image: maven
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Build with Maven
        run: mvn package --file pom.xml

  deploy:
    name: Deploy
    container:
      image: maven
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/checkout@master

      - name: Deploy with Maven
        run: |
          sed -i -e 's/AZ_USER_NAME/${AZ_USER_NAME}/' server.xml
          sed -i -e 's/AZ_PASSWORD/${AZ_PASSWORD}/' server.xml
          sed -i -e 's/AZ_TENANT_ID/${AZ_TENANT_ID}/' server.xml
          mvn --settings server.xml package azure-webapp:deploy -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        env:
          AZ_USER_NAME: ${{secrets.AZ_USER_NAME}}
          AZ_PASSWORD: ${{secrets.AZ_PASSWORD}}
          AZ_TENANT_ID: ${{secrets.AZ_TENANT}}