on:
  push:
    branches:
    - master

name:  Build and Deploy

jobs:

  build:
    name: Build
    container:
      image: maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with Maven
        run: mvn package --file pom.xml

  deploy:
    name: Deploy
    container:
      image: maven
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Deploy with Maven
        run: |
          sed -i -e 's/AZ_USER_NAME/${AZ_USER_NAME}/' server.xml
          sed -i -e 's/AZ_PASSWORD/${AZ_PASSWORD}/' server.xml
          sed -i -e 's/AZ_TENANT_ID/${AZ_TENANT_ID}/' server.xml
          # https://github.com/microsoft/azure-maven-plugins/blob/feature-spring/azure-webapp-maven-plugin/README.md
          mvn --settings server.xml package azure-webapp:deploy
        env:
          AZ_USER_NAME: ${{secrets.AZ_USER_NAME}}
          AZ_PASSWORD: ${{secrets.AZ_PASSWORD}}
          AZ_TENANT_ID: ${{secrets.AZ_TENANT_ID}}
