on: [push]

name:  Maven

jobs:

  build:
    name: Build
    container:
      image: maven
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Build with Maven
        run: mvn package --file pom.xml

  deploy:
    name: Deploy
    container:
      image: maven
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/checkout@master

      - name: Deploy with Maven
        run: mvn package azure-webapp:deploy
