name: Maven
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    actions:
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.0.0
      with:
        version-spec: 1.8
        options: -Xmx3072m

    - name: Build with Maven
      run: mvn package --file pom.xml
